### PR TITLE
#42 fix style inconsistencies

### LINKED ISSUE #42: Fix style inconsistencies
Some source files are not formatted using the current rules. To make future PRs more understandable, every existing file needs to be prettified and linted, and future commits 

@andreievg, is it a good idea to update the PR submission textbox to ensure this for all future PRs (similar to how mobile references the build number etc.)?

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #42.

### CODE REVIEW

File: src/server/database/translator.js [hunk 1]
```diff
@@ -112,26 +115,16 @@ const translateItem = recordData => {
...
-  return {
-    table: "user",
-    row: recordData
-  };
-};
+const translateUser = recordData => ({ table: "user", row: recordData });
 
-export const translateRecord = record => {
+const translateRecord = record => {
   const recordData = record.data;
```
Comment (joshxg) [inline src/server/database/translator.js]: Can we consider getting rid of this switch and replacing it with an object?
