### PR TITLE
#57 fix auth helpers

### LINKED ISSUE #57: Authorisation helpers have syntax errors
Refactored authorisation helpers have not been properly tested and have syntax errors.

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #57.

Authorisation functions have been made more explicit and JWT logic commented to make it more understandable.

### CODE REVIEW

File: src/utilities/authorisation/authorise.js [hunk 1]
```diff
@@ -1,21 +1,23 @@
...
-  // Local server authenticates using SHA-256 digest of primary server password.
-  // Random salt is added to increase the difficulty of dictionary and replay attacks.
-  const salt = crypto.randomBytes(4); // 32-bit salt
-  const auth = crypto.createHash.update(salt).update(primaryAuth);
-
-  // The salt and digest are converted to hex.
-  const saltString = salt.toString("hex");
-  const authString = auth.digest("hex");
+  // Local server authorisation is generated from hex encodings of primary authentication
+  // and randomly generated 32-bit salt salt.
```
Comment (joshxg) [inline src/utilities/authorisation/authorise.js]: comment: salt salt.

Although I don't think this comment is really necessary

File: src/utilities/authorisation/base64.js [hunk 2]
```diff
@@ -1,6 +1,17 @@
-const encode = string => Buffer.from(string).toString("base64");
-const decode = string => Buffer.from(string, "base64").toString("utf8");
+const isBuffer = input => Buffer.isBuffer(input);
+const isObject = input => typeof input === "object";
```
Comment (joshxg) [inline src/utilities/authorisation/base64.js]: This returns true for all objects - complex objects. arrays, null etc etc. I'm sure most are fine, but there are many edge cases - null, empty objects/arrays, new String('hello'). Could we also have these checks either in their own file or specific to base64 within the class if they're not needed elsewhere?

File: src/utilities/authorisation/session.js [hunk 3]
```diff
@@ -1,54 +1,76 @@
...
+   * @param {object} payload Data which uniquely identifies a given client-server session.
+   *                         This data can include anything which persists throughout the
+   *                         session and should not be modified after creation.
+   * @param {string} secret  String representing secret key used to sign and
+   *                         verify outgoing and incoming sessions.
+   */
+  constructor(payload, secret = "") {
+    // Default header representing JWT signed using SHA-256.
+    this.header = {
+      alg: "sha256", // Hash function to use for signing JWT.
```
Comment (joshxg) [inline src/utilities/authorisation/session.js]: The comments here are a little excessive..

File: src/utilities/authorisation/session.js [hunk 4]
```diff
@@ -1,54 +1,76 @@
...
     this.payload = payload;
     this.secret = secret;
-  };
+  }
 
+  /** Get JWT signature.
+   *
+   * @return {Buffer} Signature representing session fingerprint.
+   */
   get signature() {
```
Comment (joshxg) [inline src/utilities/authorisation/session.js]: again these seem over the top as comments

File: src/utilities/authorisation/session.js [hunk 5]
```diff
@@ -1,54 +1,76 @@
...
   }
 
-
+  /**
+   * Get JWT as formatted string.
+   *
+   * @return {string} Base64 encoding of dot-separated string containing each
+   *                  JWT section.
+   */
   stringify() {
```
Comment (joshxg) [inline src/utilities/authorisation/session.js]: stringify I think is sufficient and self documenting

File: src/utilities/authorisation/session.js [hunk 6]
```diff
@@ -1,54 +1,76 @@
...
 
-const isValidJwt = (jwt, secret) => {
+/**
+ * Validate JWT.
+ *
+ * @param  {Jwt}     jwt    JWT to be validated.
+ * @param  {string}  secret Secret key used to generate the JWT signature.
+ * @return {boolean}        True if the JWT can be validated, false otherwise.
+ *  */
+export const isValidJwt = (jwt, secret) => {
```
Comment (joshxg) [inline src/utilities/authorisation/session.js]: Maybe this can be a static method?

File: src/utilities/authorisation/session.js [hunk 7]
```diff
@@ -1,54 +1,76 @@
...
-// TODO: export decodeSession...
-module.exports = {
-  Jwt,
-  isValidJwt,
-  decodeSession
-}
+/**
+ * Extract header, payload and signature from stringified JWT.
+ *
+ * @param  {string} jwt Stringified JWT to be decoded and parsed.
```
Comment (joshxg) [inline src/utilities/authorisation/session.js]: this comment is wrong (and not needed in my opinion!)

File: src/utilities/authorisation/session.js [hunk 8]
```diff
@@ -1,54 +1,76 @@
...
+ * @return {object}     Object containing session header, payload and signature.
+ */
+export const decodeSession = session => {
```
Comment (joshxg) [inline src/utilities/authorisation/session.js]: Could this also be a static method? Maybe just called decode, with a parameter jwt?

File: src/utilities/requests/http.js [hunk 9]
```diff
@@ -1,12 +1,6 @@
-export const get = options => {
-  options.method = "GET";
-  return request(options, null);
-};
+/* eslint-disable no-console */
```
Comment (joshxg) [inline src/utilities/requests/http.js]: Question: We have logging in both logger.js and http.js - do these do different things?

**Comment by joshxg** [comment]
Just for reference, after successfully logging in there is a server error #63

File: src/utilities/authorisation/authorise.js (hunk 1 above)
Comment (wlthomson) [reply src/utilities/authorisation/authorise.js]: In my opinion, with crypto stuff best to make everything as explicit as possible. Comment specifies size of salt and that it is randomly generated. Will remove duplicate "salt".

File: src/utilities/authorisation/base64.js (hunk 2 above)
Comment (wlthomson) [reply src/utilities/authorisation/base64.js]: Only objects are needed to check as it doesn't make much sense to base64 these edge cases. They are there to determine between the three possible "sensible" inputs, rather than to perform error checking or sanitisation (that can be done at a later stage as is not priority right now). The checks are constants as they are not limited to base64 and may have some utility later. But for now as they are only used here, in my opinion it makes most sense to keep them here until they find a second use, rather than making a new source file which consists of only 3 lines.

File: src/utilities/authorisation/session.js (hunk 3 above)
Comment (wlthomson) [reply src/utilities/authorisation/session.js]: In my opinion, I would err on the side of too much rather than be conservative. Crypto should be as explicit as possible. It is easy to get wrong and tiny errors break everything.

File: src/utilities/authorisation/session.js (hunk 4 above)
Comment (wlthomson) [reply src/utilities/authorisation/session.js]: See above. Also, docstrings keep consistency with mobile.

File: src/utilities/authorisation/session.js (hunk 5 above)
Comment (wlthomson) [reply src/utilities/authorisation/session.js]: I think all class methods should have docstrings, it is good practice to be consistent and make crypto impossible to get wrong.

File: src/utilities/authorisation/session.js (hunk 8 above)
Comment (wlthomson) [reply src/utilities/authorisation/session.js]: I think its best to conceptually distinguish JWT from a stringified JWT session. JWT is a way of maintaining a session, but should be distinguished from the actual existing session. `isValidJwt` should be `isValidSession`. A `session` can be conceptualised as the stringified JWT. For that reason I think rename in that way and leave them in a separate namespace from the `Jwt` class as they are semantically different entities. 

It will also look clearer when the functions are used to not be using the class to create a JWT object and also calling static methods on that class. Also, there are situations where you will only be importing one of the other so it keeps it a bit more modular. If they end up always appearing together, then I think static methods would be the way to go at that point.

File: src/utilities/requests/http.js (hunk 9 above)
Comment (wlthomson) [reply src/utilities/requests/http.js]: The `http.js` was from a while ago, the logger is more recent and is a middleware for express (so it might not be suitable for front-end logging, but maybe could be if designed well?).

File: src/utilities/authorisation/authorise.js [hunk 10]
```diff
@@ -1,21 +1,23 @@
-const base64 = require("./base64");
+import base64 from "./base64";
```
[the remark this answers is not in the document]
Comment (wlthomson) [reply src/utilities/authorisation/authorise.js]: Good spot. Will add missing import.

File: src/utilities/authorisation/session.js (hunk 6 above)
Comment (wlthomson) [reply src/utilities/authorisation/session.js]: I think that could be a good idea, but they might be imported independently. See discussion below.

**Comment by wlthomson** [comment]
> Just for reference, after successfully logging in there is a server error #63

Thanks, will check it out.

File: src/utilities/authorisation/session.js (hunk 7 above)
Comment (joshxg) [reply src/utilities/authorisation/session.js]: ya

File: src/utilities/requests/http.js (hunk 9 above)
Comment (joshxg) [reply src/utilities/requests/http.js]: Are we able to choose one or the other and either remove logger.js if we will just use the logging in http.js in this pr, or if we are removing the logging from http.js, make an issue for that?

File: src/utilities/authorisation/session.js (hunk 8 above)
Comment (joshxg) [reply src/utilities/authorisation/session.js]: So a session is only the JWT stored as a different data type - I think this is the same thing, personally. 

I think it would be good as a static class called JWT, with the method names being toString, isValid, decode

**Comment by joshxg** [comment]
Can we make this high priority as it is blocking any attempts to use the back-end api

File: src/utilities/authorisation/session.js (hunk 8 above)
Comment (wlthomson) [reply src/utilities/authorisation/session.js]: Yeah, the session is the serialised JWT, basically. The problem with `decode` is that the JWT is an object, so it never needs to be "decoded", you can just get the fields in the normal way. So that is a helper for session strings. The logic for `isValid` is for convenience. Putting it in the class would mean having to construct a `Jwt` every time you get a session string, just to validate it (it would also mean having to be a bit hacky and store the existing signature and then change the secret and recalculate and see if they match, which mutates the `Jwt` state).

So, I think rename them to specify session in the names, and make them static (but leave the `Jwt` class as an instance, because a `Jwt` is best as a class instance which can have a constructor and getters etc. rather than an object with fields).

File: src/utilities/requests/http.js (hunk 9 above)
Comment (wlthomson) [reply src/utilities/requests/http.js]: The `logger.js` is the middleware used by express, so its designed for that with a specific interface. Thats why its under the `server` directory. It would be good to have one logger for everything, but I'm not sure if axios will expose the same sort of objects. If axios and express both use the same node objects behind the scenes (which I think its likely), then it will probably work.

**Comment by wlthomson** [comment]
Will do it asap.

**Comment by joshxg** [comment]
Looks nice. Have tested with some requests code from another branch and it works well. Thanks :)
