### PR TITLE
#73 login

### LINKED ISSUE #73: Integration with api - login
References #72 

Login needs to be integrated with the API.

Requirements:

- On login attempt, encode the username and password (using getAuthorisation utility) and send as an Authorization header.
- On an incorrect username or password, feedback should be given to the user and another attempt should not be available until modifications to the current username and password have been made.
- On either a server error or network error, throw an error (To be caught by a wrapping error boundary to display a fallback UI).
- On a successful login, a serialized JWT is stored in the authContext, while the username and store for a given user are stored in the userContext.

### PR DESCRIPTION
**Pull request by joshxg**
fixes #73

### CODE REVIEW

File: src/ui/components/Modals/LoginModal.js [hunk 1]
```diff
@@ -42,24 +43,36 @@ class LoginModal extends React.Component {
...
-    let session;
     try {
-      const { data } = await request({
+      const response = await request({
         endpoint: "login",
-        auth: getAuthorisation("user", "password"),
+        auth: getAuthorisation(username, password),
+      });
+      const { data } = response;
+      const { session, payload } = JWT.deserialise(data.session);
```
Comment (wlthomson) [inline src/ui/components/Modals/LoginModal.js]: `JWT.deserialise` returns a new `JWT` object. Here `session` will be undefined. Although `payload` will have a value, this is meant to be treated like a private member of the `JWT` object. Suggest the handle logic only returns the `JWT` object. `handleLogin` in `MSupplyRnR.js` can then extract the relevant fields using `jwt.getField(...)`.

Suggest that `auth` in the `MSupplyRnR` state can just be `jwt`, as that object will contain all session data. More specific data, such as `username` and `storeName` etc. can be extracted using `getField(...)`. Can also add a method `getFields()` to `JWT` if this would be convenient (which would essentially just return the payload, but respect the `JWT` encapsulation).

File: src/ui/MSupplyRnR.js [hunk 2]
```diff
@@ -17,38 +17,45 @@ class MSupplyRnR extends React.Component {
...
-      sessionId: null,
+      auth: null,
     };
   }
 
-  handleSuccesfulLogin = (sessionId, user) => {
-    // no authentication is attempted.
-    this.setState({ loginModalOpen: false, sessionId, user });
+  handleLogin = ({ session, payload }) => {
+    const { username, storeName, supplyingStoreName } = payload;
```
Comment (wlthomson) [inline src/ui/MSupplyRnR.js]: Just documenting that username not currently in payload, but as we discussed will be fixed by #85.

File: src/ui/components/Modals/LoginModal.js (hunk 1 above)
Comment (joshxg) [reply src/ui/components/Modals/LoginModal.js]: Added a fix for the JWT logic. I think getFields might be useful, but not urgent.

Have added a jwt field to the auth context. However have kept the session field also as this just makes requests simpler.

File: src/ui/components/Modals/LoginModal.js [hunk 3]
```diff
@@ -51,12 +51,12 @@ class LoginModal extends React.Component {
         auth: getAuthorisation(username, password),
       });
       const { data } = response;
-      const { session, payload } = JWT.deserialise(data.session);
-      // const { session, payload } = data;
+      const { session } = data;
+      const jwt = JWT.deserialise(data.session);
```
Comment (wlthomson) [inline src/ui/components/Modals/LoginModal.js]: Can this just be `JWT.deserialise(session)`, since data is already destructured?

Comment (joshxg) [reply src/ui/components/Modals/LoginModal.js]: yup, good catch thanks. Fixed
